// DebugWatchValueJsonEncodingDefs.h
// Defs for the Json encoder / decoder.
// Debug expession evaluator.
// Giannhs Apostolidhs, April 2013.
//

#ifndef	DEBUGWATCHVALUEJSONENCODINGDEFS_H
#define	DEBUGWATCHVALUEJSONENCODINGDEFS_H

#include "DebugWatchValueEncodingDefs.h"

//////////////////////////////////////////////////////////////////

#define	JSON_ENCODING_ID		"json"

#define	JSON_KWD_SIMPLE			ENCODING_TAG_SIMPLE		
#define	JSON_KWD_COMPOSITE		ENCODING_TAG_COMPOSITE	
#define	JSON_KWD_DESC			ENCODING_TAG_DESC		
#define	JSON_KWD_NODESC			ENCODING_TAG_NODESC		
#define	JSON_KWD_VISIBLE		ENCODING_TAG_VISIBLE	
#define	JSON_KWD_HIDDEN			ENCODING_TAG_HIDDEN		
#define	JSON_KWD_NOKEYREF		ENCODING_TAG_NOKEYREF	
#define	JSON_KWD_KEYREF			ENCODING_TAG_KEYREF
#define	JSON_KWD_NOKEYTYPE		ENCODING_TAG_NOKEYTYPE
#define	JSON_KWD_KEYTYPE		ENCODING_TAG_KEYTYPE
#define	JSON_VAL_SIZE			ENCODING_TAG_SIZE
#define	JSON_VAL_TYPE			ENCODING_TAG_TYPE		
#define	JSON_VAL_VALUE			ENCODING_TAG_VALUE
#define	JSON_VAL_SUBINDEX		ENCODING_TAG_SUBINDEX		
#define	JSON_VAL_OVERVIEW		ENCODING_TAG_OVERVIEW		
#define	JSON_VAL_ABSOLUTEREF	ENCODING_TAG_ABSOLUTEREF		
#define	JSON_VAL_DISPLAYDESC	ENCODING_TAG_DISPLAYDESC
#define	JSON_VAL_KEYTYPEINFO	ENCODING_TAG_KEYTYPEINFO
#define	JSON_VAL_KEYACCESS		ENCODING_TAG_KEYACCESS
#define	JSON_VAL_FIELDKEYS		ENCODING_TAG_FIELDKEYS
#define	JSON_VAL_DISPLAYEDKEY	ENCODING_TAG_DISPLAYEDKEY
#define	JSON_VAL_KEYCONTENTREF	ENCODING_TAG_KEYCONTENTREF
#define	JSON_VAL_CONTENTS		ENCODING_TAG_CONTENTS	

//////////////////////////////////////////////////////////////////

#endif	// Do not add stuff beyond this point.