// DebugWatchValueXmlEncodingDefs.h
// Defs for the Xml encoder / decoder.
// ScriptFighter Project.
// Debug expession evaluator.
// A. Savidis, August 2008.
//

#ifndef	DEBUGWATCHVALUEXMLENCODINGDEFS_H
#define	DEBUGWATCHVALUEXMLENCODINGDEFS_H

#include "DebugWatchValueEncodingDefs.h"

//////////////////////////////////////////////////////////////////

#define	XML_ENCODING_ID			"xml"

#define	XML_KWD_SIMPLE			ENCODING_TAG_SIMPLE			
#define	XML_KWD_COMPOSITE		ENCODING_TAG_COMPOSITE		
#define	XML_KWD_DESC			ENCODING_TAG_DESC			
#define	XML_KWD_NODESC			ENCODING_TAG_NODESC			
#define	XML_KWD_VISIBLE			ENCODING_TAG_VISIBLE		
#define	XML_KWD_HIDDEN			ENCODING_TAG_HIDDEN			
#define	XML_KWD_NOKEYREF		ENCODING_TAG_NOKEYREF		
#define	XML_KWD_KEYREF			ENCODING_TAG_KEYREF			
#define	XML_KWD_NOKEYTYPE		ENCODING_TAG_NOKEYTYPE
#define	XML_KWD_KEYTYPE			ENCODING_TAG_KEYTYPE
#define	XML_ATTR_TYPE			ENCODING_TAG_TYPE						
#define	XML_ATTR_VALUE			ENCODING_TAG_VALUE			
#define	XML_ATTR_SUBINDEX		ENCODING_TAG_SUBINDEX

#define	XML_ELEM_OVERVIEW		ENCODING_TAG_OVERVIEW		
#define	XML_ELEM_ABSOLUTEREF	ENCODING_TAG_ABSOLUTEREF	
#define	XML_ELEM_VALUE			ENCODING_TAG_VALUE
#define	XML_ELEM_CONTENT		ENCODING_TAG_CONTENT		
#define	XML_ELEM_CONTENTS		ENCODING_TAG_CONTENTS		
#define	XML_ELEM_FIELDKEYS		ENCODING_TAG_FIELDKEYS		
#define	XML_ELEM_FIELDKEY		ENCODING_TAG_FIELDKEY		
#define	XML_ELEM_KEYACCESS		ENCODING_TAG_KEYACCESS		
#define	XML_ELEM_DISPLAYEDKEY	ENCODING_TAG_DISPLAYEDKEY	
#define	XML_ELEM_KEYCONTENTREF	ENCODING_TAG_KEYCONTENTREF	
#define	XML_ELEM_KEYTYPEINFO	ENCODING_TAG_KEYTYPEINFO
#define	XML_ELEM_DISPLAYDESC	ENCODING_TAG_DISPLAYDESC	

//////////////////////////////////////////////////////////////////

#endif	// Do not add stuff beyond this point.
