copy  "%DELTA%\DLLs\BytecodeStructures\lib\debug\BytecodeStructuresD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\ReadersWriters\lib\debug\ReadersWritersD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerBackend\lib\debug\DebuggerBackendD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerCommon\lib\debug\DebuggerCommonD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerFrontend\lib\debug\DebuggerFrontendD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\SocketLib\lib\debug\SocketsD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\UtilAndDebugLib\lib\debug\UtilAndDefensiveHeapD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\SyntaxTree\lib\debug\SyntaxTreeD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\CompilerComponents\lib\debug\CompilerComponentsD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\VirtualMachineComponents\lib\debug\VirtualMachineComponentsD.dll" "..\..\Build"
copy  "%DELTA%\DeltaExtraLibraries\JSONParser\lib\debug\JSONParserD.dll" "..\..\Build"
copy  "%DELTA%\DeltaExtraLibraries\XMLParser\lib\debug\XMLParserD.dll" "..\..\Build\extension_dlls"
copy  "%DELTA%\DeltaExtraLibraries\JSONParser\lib\debug\JSONParserD.dll" "..\..\Build\extension_dlls"

