copy  "%DELTA%\DLLs\BytecodeStructures\lib\release\BytecodeStructures.dll" "..\..\Build"
copy  "%DELTA%\DLLs\ReadersWriters\lib\release\ReadersWriters.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerBackend\lib\release\DebuggerBackend.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerCommon\lib\release\DebuggerCommon.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerFrontend\lib\release\DebuggerFrontend.dll" "..\..\Build"
copy  "%DELTA%\DLLs\SocketLib\lib\release\Sockets.dll" "..\..\Build"
copy  "%DELTA%\DLLs\UtilAndDebugLib\lib\release\UtilAndDefensiveHeap.dll" "..\..\Build"
copy  "%DELTA%\DLLs\SyntaxTree\lib\release\SyntaxTree.dll" "..\..\Build"
copy  "%DELTA%\DLLs\CompilerComponents\lib\release\CompilerComponents.dll" "..\..\Build"
copy  "%DELTA%\DLLs\VirtualMachineComponents\lib\release\VirtualMachineComponents.dll" "..\..\Build"
copy  "%DELTA%\DeltaExtraLibraries\JSONParser\lib\release\JSONParser.dll" "..\..\Build"
copy  "%DELTA%\DeltaExtraLibraries\XMLParser\lib\release\XMLParser.dll" "..\..\Build\extension_dlls"
copy  "%DELTA%\DeltaExtraLibraries\JSONParser\lib\release\JSONParser.dll" "..\..\Build\extension_dlls"

