copy "..\Delta\DLLs\BytecodeStructures\lib\release\BytecodeStructures.dll" "..\..\Build"
copy "..\Delta\DLLs\ReadersWriters\lib\release\ReadersWriters.dll" "..\..\Build"
copy "..\Delta\DLLs\DebuggerBackend\lib\release\DebuggerBackend.dll" "..\..\Build"
copy "..\Delta\DLLs\DebuggerCommon\lib\release\DebuggerCommon.dll" "..\..\Build"
copy "..\Delta\DLLs\DebuggerFrontend\lib\release\DebuggerFrontend.dll" "..\..\Build"
copy "..\Delta\DLLs\SocketLib\lib\release\Sockets.dll" "..\..\Build"
copy "..\Delta\DLLs\UtilAndDebugLib\lib\release\UtilAndDefensiveHeap.dll" "..\..\Build"
copy "..\Delta\DLLs\SyntaxTree\lib\release\SyntaxTree.dll" "..\..\Build"
copy "..\Delta\DLLs\CompilerComponents\lib\release\CompilerComponents.dll" "..\..\Build"
copy "..\Delta\DLLs\VirtualMachineComponents\lib\release\VirtualMachineComponents.dll" "..\..\Build"

