copy  "%DELTA%\DLLs\BytecodeStructures\lib\debug\BytecodeStructuresD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\ReadersWriters\lib\debug\ReadersWritersD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerBackend\lib\debug\DebuggerBackendD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerCommon\lib\debug\DebuggerCommonD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\DebuggerFrontend\lib\debug\DebuggerFrontendD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\SocketLib\lib\debug\SocketsD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\UtilAndDebugLib\lib\debug\UtilAndDefensiveHeapD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\SyntaxTree\lib\debug\SyntaxTreeD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\CompilerComponents\lib\debug\CompilerComponentsD.dll" "..\..\Build"
copy  "%DELTA%\DLLs\VirtualMachineComponents\lib\debug\VirtualMachineComponentsD.dll" "..\..\Build"

