#define yy_create_buffer DeltaCompiler_yy_create_buffer
#define yy_delete_buffer DeltaCompiler_yy_delete_buffer
#define yy_scan_buffer DeltaCompiler_yy_scan_buffer
#define yy_scan_string DeltaCompiler_yy_scan_string
#define yy_scan_bytes DeltaCompiler_yy_scan_bytes
#define yy_flex_debug DeltaCompiler_yy_flex_debug
#define yy_init_buffer DeltaCompiler_yy_init_buffer
#define yy_flush_buffer DeltaCompiler_yy_flush_buffer
#define yy_load_buffer_state DeltaCompiler_yy_load_buffer_state
#define yy_switch_to_buffer DeltaCompiler_yy_switch_to_buffer
#define yyin DeltaCompiler_yyin
#define yyleng DeltaCompiler_yyleng
#define yylex DeltaCompiler_yylex
#define yyout DeltaCompiler_yyout
#define yyrestart DeltaCompiler_yyrestart
#define yytext DeltaCompiler_yytext
#define yywrap DeltaCompiler_yywrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
static yyconst short int yy_accept[223] =
    {   0,
       79,   79,   92,   90,   79,   80,   90,   87,   35,   40,
       90,   38,   36,   37,   64,   39,   81,   81,   90,   78,
       42,   47,   41,   34,   82,   90,   90,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   79,   43,    0,   77,   54,   48,   75,   52,
       62,   73,   50,   63,   74,   51,   65,   67,   88,   89,
       76,   53,    0,   81,    0,   61,   46,   56,    0,   44,
       45,   55,   83,   83,   83,   83,   83,   82,   71,   72,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   12,
       82,   82,   82,   82,   82,   82,   20,   82,   82,   82,

       82,   82,   82,   82,   57,    0,   66,    0,   68,   84,
       85,   60,   49,   58,   59,   83,   83,   83,   83,   83,
       18,   82,   82,   82,   82,   82,   82,   15,   82,   82,
       82,   82,   17,   19,   82,   82,   82,   82,   82,   82,
       82,   26,   82,   82,    0,   70,   69,   31,   83,   83,
       83,   30,   82,   82,   82,   82,   82,   13,   82,   82,
       82,   82,   82,   82,   82,   82,    8,   82,   82,   27,
       21,   82,   82,    0,   83,   83,   33,   82,   82,   23,
       11,   82,   22,   82,   82,   82,   25,   82,   82,   82,
       82,   28,   29,   14,   86,   83,   83,   82,    3,   82,

       82,   82,    4,    7,   82,    2,   10,   86,    5,   83,
       82,   82,   16,   82,    6,   83,   82,   24,    1,   32,
        9,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    1,    1,    8,
        9,   10,   11,    1,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,   22,   23,   23,   23,   23,   23,   23,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       25,    1,   26,    1,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   24,   37,   38,   39,   40,
       41,   42,   24,   43,   44,   45,   46,   47,   48,   49,
       50,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    1,    1,    1,    1,
        1,    1,    4,    5,    1,    1,    6,    4,    4,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[228] =
    {   0,
        0,    0,  259,  260,  256,  260,  237,  260,  254,   31,
      246,   32,   42,   43,   41,   46,   52,   59,  237,  260,
       37,   63,   57,   44,    0,  228,  226,   36,  208,  209,
      211,   53,  215,   59,  215,   50,   49,  214,   58,   61,
      201,  209,  241,  215,   91,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  228,   89,  260,  260,
      260,  260,   95,   99,    0,  260,  213,  260,  230,  211,
      210,  260,    0,  204,  207,  192,  201,    0,  260,  260,
      201,  197,  186,  197,  188,  183,  188,  182,  184,    0,
      184,  192,  176,  182,  174,  186,    0,  172,  178,  187,

      171,   67,  177,  176,  260,  103,  260,  202,  183,  105,
        0,  260,  260,  260,  260,    0,  164,  169,  175,   78,
        0,  160,  173,  176,   80,  171,  158,  169,  170,  170,
      170,  162,    0,    0,  149,  149,  161,  148,  151,  149,
      158,    0,  149,  150,  124,  260,  260,    0,  158,  143,
      152,    0,  145,  140,  145,  136,  144,    0,  147,  150,
      132,  145,  137,  133,  141,  129,    0,  135,  122,    0,
        0,  135,  136,    0,  136,  138,    0,  133,  119,    0,
        0,  123,    0,  132,  125,  132,    0,  128,  118,  117,
      126,    0,    0,    0,  153,  126,  108,  112,    0,  105,

      115,  108,    0,    0,  103,    0,    0,  141,    0,   87,
       82,   90,    0,   68,    0,   59,   54,    0,    0,    0,
        0,  260,  126,  129,  133,  135,  141
    } ;

static yyconst short int yy_def[228] =
    {   0,
      222,    1,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  223,  224,  222,  222,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  225,  222,  222,  222,  222,  222,
      222,  222,  226,  226,  226,  226,  226,  224,  222,  222,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,

      224,  224,  224,  224,  222,  222,  222,  222,  222,  222,
      225,  222,  222,  222,  222,  226,  226,  226,  226,  226,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  222,  222,  222,  226,  226,  226,
      226,  226,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  227,  226,  226,  226,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  227,  226,  226,  224,  224,  224,

      224,  224,  224,  224,  224,  224,  224,  227,  226,  226,
      224,  224,  224,  224,  224,  226,  224,  224,  224,  226,
      224,    0,  222,  222,  222,  222,  222
    } ;

static yyconst short int yy_nxt[311] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,    4,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   25,   26,   27,    4,   28,   29,   30,
       25,   31,   32,   25,   25,   33,   25,   34,   35,   36,
       37,   25,   38,   39,   40,   41,   25,   42,   25,   25,
       46,   49,   51,   57,   54,   59,   67,   47,   50,   60,
       58,   52,   55,   68,   63,   61,   64,   64,   53,   56,
       69,   63,   62,   64,   64,   81,   71,   74,   82,   83,
       87,   75,   70,   72,   76,   94,   91,   77,   96,   99,
       95,   97,   45,   88,  140,  101,  108,  221,   89,   92,

       65,  220,  100,  102,  145,  106,  106,  219,  109,  110,
      110,   63,  141,   64,   64,  151,  142,  106,  106,  110,
      110,  218,  152,  156,  157,  145,  217,  216,  174,   73,
       73,   78,   78,   78,   78,  111,  111,  116,  116,  116,
      116,  195,  208,  195,  195,  195,  195,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  200,  199,  198,  197,  196,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,

      160,  159,  158,  155,  154,  153,  150,  149,  148,  147,
      146,  144,  143,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  115,  114,  113,  112,
      107,  105,   43,  104,  103,   98,   93,   90,   86,   85,
       84,   80,   79,   66,   48,   45,   44,   43,  222,    3,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222
    } ;

static yyconst short int yy_chk[311] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       10,   12,   13,   15,   14,   16,   21,   10,   12,   16,
       15,   13,   14,   21,   17,   16,   17,   17,   13,   14,
       22,   18,   16,   18,   18,   28,   23,   24,   28,   28,
       32,   24,   22,   23,   24,   36,   34,   24,   37,   39,
       36,   37,   45,   32,  102,   40,   58,  217,   32,   34,

       17,  216,   39,   40,  106,   45,   45,  214,   58,   63,
       63,   64,  102,   64,   64,  120,  102,  106,  106,  110,
      110,  212,  120,  125,  125,  145,  211,  210,  145,  223,
      223,  224,  224,  224,  224,  225,  225,  226,  226,  226,
      226,  227,  208,  227,  227,  227,  227,  205,  202,  201,
      200,  198,  197,  196,  195,  191,  190,  189,  188,  186,
      185,  184,  182,  179,  178,  176,  175,  173,  172,  169,
      168,  166,  165,  164,  163,  162,  161,  160,  159,  157,
      156,  155,  154,  153,  151,  150,  149,  144,  143,  141,
      140,  139,  138,  137,  136,  135,  132,  131,  130,  129,

      128,  127,  126,  124,  123,  122,  119,  118,  117,  109,
      108,  104,  103,  101,  100,   99,   98,   96,   95,   94,
       93,   92,   91,   89,   88,   87,   86,   85,   84,   83,
       82,   81,   77,   76,   75,   74,   71,   70,   69,   67,
       57,   44,   43,   42,   41,   38,   35,   33,   31,   30,
       29,   27,   26,   19,   11,    9,    7,    5,    3,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,

      222,  222,  222,  222,  222,  222,  222,  222,  222,  222
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "..\\DeltaLexAnalyser.l"
#define INITIAL 0
#line 2 "..\\DeltaLexAnalyser.l"
// Lexical analyser of the Delta language.
// ScriptFighter Project.
// A. Savidis, Start October 1999.
// Updates for reading quoted strings and some refactoring, February 2009.
//

#include <cstring>
#include <cstdio>
#include <ctype.h>

#include "DDebug.h"
#include "Expr.h"
#include "Symbol.h"
#include "ParseActions.h"
#include "DeltaByteCodeTypes.h"
#include "ulexutil.h"
#include "DeltaCompErrorMsg.h"
#include "DeltaParser.h"
#include "CompilerAPI.h"
#include "ParseActions.h"

#define	YY_SKIP_YYWRAP
#define YY_USE_PROTOS
#define	YY_NEVER_INTERACTIVE 1

// Must be static local since every lexer
// has its own scan buffer.

static void* lexBufferState = (void*) 0;

bool DeltaCompiler::InitialiseForText (const char* text) {
	DASSERT(!lexBufferState);
	lexBufferState		= DeltaCompiler_yy_scan_string(text);
	*DPTR(srcFile)		= DBG_DYNAMIC_SOURCE;
	*DPTR(dynamicCode)	= text;
	isDynamicCode		= true;
	return true;
}

void DeltaCompiler::CleanUpForText (void) {
	if (lexBufferState) {
		DeltaCompiler_yy_flush_buffer((YY_BUFFER_STATE) lexBufferState);
		DeltaCompiler_yy_delete_buffer((YY_BUFFER_STATE) lexBufferState);
		unullify(lexBufferState);
	}
}

// The yylex() must be re-entrant, so it takes
// yylval as a formal parameter.
//
#define YY_DECL		int DeltaCompiler_yylex (void* yylval)
#define	STACKVAL	((YYSTYPE*) yylval)
#define	yywrap		DeltaCompiler_yywrap

// Lexical analysis helpers.
//
static void					IgnoreCStyleComments (void);
static void					IgnoreCPPStyleComments (void);
static const std::string	ReadQuotedString (void);

extern int DeltaCompiler_yywrap(void);

#line 584 "lex.DeltaCompiler_yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 79 "..\\DeltaLexAnalyser.l"


#line 734 "lex.DeltaCompiler_yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 223 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 260 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 81 "..\\DeltaLexAnalyser.l"
return  FUNCTION;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "..\\DeltaLexAnalyser.l"
return	RETURN;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "..\\DeltaLexAnalyser.l"
return	ASSERT;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "..\\DeltaLexAnalyser.l"
return	LAMBDA;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "..\\DeltaLexAnalyser.l"
return	LAMBDA_REF;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 86 "..\\DeltaLexAnalyser.l"
return	ONEVENT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "..\\DeltaLexAnalyser.l"
return	METHOD;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 88 "..\\DeltaLexAnalyser.l"
return	SELF;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "..\\DeltaLexAnalyser.l"
return	ARGUMENTS;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "..\\DeltaLexAnalyser.l"
return	STATIC;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 91 "..\\DeltaLexAnalyser.l"
return	CONST;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 92 "..\\DeltaLexAnalyser.l"
return	IF;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 93 "..\\DeltaLexAnalyser.l"
return	ELSE;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 94 "..\\DeltaLexAnalyser.l"
return	WHILE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 95 "..\\DeltaLexAnalyser.l"
return	FOR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "..\\DeltaLexAnalyser.l"
return	FOREACH;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "..\\DeltaLexAnalyser.l"
return	NIL;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "..\\DeltaLexAnalyser.l"
return	AND;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "..\\DeltaLexAnalyser.l"
return	NOT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "..\\DeltaLexAnalyser.l"
return	OR;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "..\\DeltaLexAnalyser.l"
return	TRUE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "..\\DeltaLexAnalyser.l"
return	FALSE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "..\\DeltaLexAnalyser.l"
return	BREAK;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "..\\DeltaLexAnalyser.l"
return	CONTINUE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "..\\DeltaLexAnalyser.l"
return	LOCAL;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "..\\DeltaLexAnalyser.l"
return	TRY;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "..\\DeltaLexAnalyser.l"
return	TRAP;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "..\\DeltaLexAnalyser.l"
return	THROW;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "..\\DeltaLexAnalyser.l"
return	USING;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "..\\DeltaLexAnalyser.l"
return	SET;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "..\\DeltaLexAnalyser.l"
return	GET;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "..\\DeltaLexAnalyser.l"
return	OPERATOR;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "..\\DeltaLexAnalyser.l"
return	NEWSELF;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "..\\DeltaLexAnalyser.l"
return	ATTRIBUTE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "..\\DeltaLexAnalyser.l"
return	STRINGIFY;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "..\\DeltaLexAnalyser.l"
return	ADD;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "..\\DeltaLexAnalyser.l"
return	SUB;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "..\\DeltaLexAnalyser.l"
return	MUL;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "..\\DeltaLexAnalyser.l"
return	DIV;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "..\\DeltaLexAnalyser.l"
return	MOD;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "..\\DeltaLexAnalyser.l"
return	GT;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "..\\DeltaLexAnalyser.l"
return	LT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "..\\DeltaLexAnalyser.l"
return	NE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "..\\DeltaLexAnalyser.l"
return	EQ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "..\\DeltaLexAnalyser.l"
return	GE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "..\\DeltaLexAnalyser.l"
return	LE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 128 "..\\DeltaLexAnalyser.l"
return	ASSIGN;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 129 "..\\DeltaLexAnalyser.l"
return	CALL;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 130 "..\\DeltaLexAnalyser.l"
return	CAST;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 131 "..\\DeltaLexAnalyser.l"
return	ADD_POSTFIX;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 132 "..\\DeltaLexAnalyser.l"
return	SUB_POSTFIX;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 133 "..\\DeltaLexAnalyser.l"
return	MUL_POSTFIX;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 134 "..\\DeltaLexAnalyser.l"
return	DIV_POSTFIX;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 135 "..\\DeltaLexAnalyser.l"
return	MOD_POSTFIX;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 136 "..\\DeltaLexAnalyser.l"
return	GT_POSTFIX;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 137 "..\\DeltaLexAnalyser.l"
return	LT_POSTFIX;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 138 "..\\DeltaLexAnalyser.l"
return	NE_POSTFIX;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 139 "..\\DeltaLexAnalyser.l"
return	EQ_POSTFIX;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 140 "..\\DeltaLexAnalyser.l"
return	GE_POSTFIX;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 141 "..\\DeltaLexAnalyser.l"
return	LE_POSTFIX;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 143 "..\\DeltaLexAnalyser.l"
return	GLOBAL_SCOPE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 144 "..\\DeltaLexAnalyser.l"
return	PLUSPLUS;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 145 "..\\DeltaLexAnalyser.l"
return	MINUSMINUS;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 146 "..\\DeltaLexAnalyser.l"
return	DOT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 147 "..\\DeltaLexAnalyser.l"
return	DOUBLE_DOT;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 148 "..\\DeltaLexAnalyser.l"
return	TRIPLE_DOT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 149 "..\\DeltaLexAnalyser.l"
return	DOT_ASSIGN;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 150 "..\\DeltaLexAnalyser.l"
return	DOT_EQUAL;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 151 "..\\DeltaLexAnalyser.l"
return	DOT_EQUAL_RHS;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 152 "..\\DeltaLexAnalyser.l"
return	DOT_CAST;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 153 "..\\DeltaLexAnalyser.l"
return	DOUBLE_LB;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 154 "..\\DeltaLexAnalyser.l"
return	DOUBLE_RB;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 155 "..\\DeltaLexAnalyser.l"
return	ADD_A;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 156 "..\\DeltaLexAnalyser.l"
return	SUB_A;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 157 "..\\DeltaLexAnalyser.l"
return	MUL_A;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 158 "..\\DeltaLexAnalyser.l"
return	DIV_A;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 159 "..\\DeltaLexAnalyser.l"
return	MOD_A;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 160 "..\\DeltaLexAnalyser.l"
return	SEMI;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 162 "..\\DeltaLexAnalyser.l"
{}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 164 "..\\DeltaLexAnalyser.l"
{	DeltaCompiler::NextLine(); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 166 "..\\DeltaLexAnalyser.l"
{	ucastassign(STACKVAL->numberConst, ustrdectodouble(yytext));
					return NUMBER_CONST;
				}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "..\\DeltaLexAnalyser.l"
{	STACKVAL->id = usaveidstr(yytext);
					return IDENT;
				}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 174 "..\\DeltaLexAnalyser.l"
{	STACKVAL->id = usaveidstr(yytext);
					return ATTRIBUTE_IDENT;
				}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 178 "..\\DeltaLexAnalyser.l"
{	ucastassign(STACKVAL->numberConst, ustrfracttodouble(yytext));
					return NUMBER_CONST;
				}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 182 "..\\DeltaLexAnalyser.l"
{	ucastassign(STACKVAL->numberConst, ustrtohex(yytext + 2));
					return NUMBER_CONST;
				}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 186 "..\\DeltaLexAnalyser.l"
{	util_ui32 line;
					sscanf(yytext + 1, "%u", &line);
					DeltaCompiler::SetLine(line);
					DeltaCompSetCurrentFile(DNULLCHECK(strchr(yytext, '\"')) + 1);
					while (yyinput() != '\n'){} // Read until end of line.
				}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 193 "..\\DeltaLexAnalyser.l"
{	STACKVAL->strConst = Translate_StringWithLateDestruction(ucopystr(ReadQuotedString()));
					return STRING_CONST;
				}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 197 "..\\DeltaLexAnalyser.l"
{	IgnoreCStyleComments();		}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 198 "..\\DeltaLexAnalyser.l"
{	IgnoreCPPStyleComments();	}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 200 "..\\DeltaLexAnalyser.l"
return yytext[0];
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 202 "..\\DeltaLexAnalyser.l"
ECHO;
	YY_BREAK
#line 1289 "lex.DeltaCompiler_yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 223 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 223 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 222);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 202 "..\\DeltaLexAnalyser.l"


//------------------------------------------------------------------

int					DeltaCompiler_yywrap (void)			{ return 1; }
void				DeltaCompiler_ResetLex (FILE* fp)	{ yyrestart(fp); }
const std::string	DeltaCompiler_GetText (void)		{ return yytext; }

static char input_wrapper (void)	{ return yyinput(); }
static void unput_wrapper (char c)	{ unput(c); }

static void IgnoreCStyleComments (void)  {
	util_ui32 line = DeltaCompiler::GetLine();
	uignoreCcomments(input_wrapper, unput_wrapper, &line, &DeltaCompError);
	DeltaCompiler::SetLine(line);
} 

static void IgnoreCPPStyleComments (void) {
	util_ui32 line = DeltaCompiler::GetLine();
	uignoreCPPcomments(input_wrapper, &line);
	DeltaCompiler::SetLine(line);
}

static const std::string ReadQuotedString (void) {
	util_ui32 line = DeltaCompiler::GetLine();
	std::string s;
	ureadquotedstring(s, input_wrapper, &line, &DeltaCompError);
	DeltaCompiler::SetLine(line);
	return uextendescapesequences(s.c_str());
}

//------------------------------------------------------------------
