#define yyFlexLexer DeltaScannerFlexLexer

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>
using namespace std;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include "DeltaScanner.h"


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
static yyconst short int yy_accept[228] =
    {   0,
       85,   85,   98,   96,   85,   86,   82,   93,   35,   84,
       40,   83,   96,   38,   36,   37,   64,   39,   87,   87,
       96,   78,   42,   47,   41,   34,   88,   96,   96,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   81,   85,   43,    0,   77,   54,
       48,   75,   52,   62,   73,   50,   63,   74,   51,   65,
       67,   94,   95,   76,   53,    0,   87,    0,   61,   79,
       46,   56,    0,   44,   45,   80,   55,   89,   89,   89,
       89,   89,   88,   71,   72,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   12,   88,   88,   88,   88,   88,

       88,   20,   88,   88,   88,   88,   88,   88,   88,   57,
        0,   66,    0,   68,   90,   91,   60,   49,   58,   59,
       89,   89,   89,   89,   89,   18,   88,   88,   88,   88,
       88,   88,   15,   88,   88,   88,   88,   17,   19,   88,
       88,   88,   88,   88,   88,   88,   26,   88,   88,    0,
       70,   69,   31,   89,   89,   89,   30,   88,   88,   88,
       88,   88,   13,   88,   88,   88,   88,   88,   88,   88,
       88,    8,   88,   88,   27,   21,   88,   88,    0,   89,
       89,   33,   88,   88,   23,   11,   88,   22,   88,   88,
       88,   25,   88,   88,   88,   88,   28,   29,   14,   92,

       89,   89,   88,    3,   88,   88,   88,    4,    7,   88,
        2,   10,   92,    5,   89,   88,   88,   16,   88,    6,
       89,   88,   24,    1,   32,    9,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,    1,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,   24,   25,   25,   25,   25,   25,   25,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       27,    1,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   26,   39,   40,   41,   42,
       43,   44,   26,   45,   46,   47,   48,   49,   50,   51,
       52,   26,    1,    1,    1,   53,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    1,    4,    5,    1,    1,    6,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1
    } ;

static yyconst short int yy_base[233] =
    {   0,
        0,    0,  264,  265,  261,  265,  240,  265,  259,  265,
       32,  265,  249,   33,   43,   44,   42,   47,   53,   60,
      240,  265,   58,   64,   59,   49,    0,  231,  229,   48,
      211,  212,  214,   53,  218,   54,  218,   60,   57,  217,
       66,   69,  204,  212,  265,  246,  218,  103,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  231,
       97,  265,  265,  265,  265,   91,  100,    0,  265,  265,
      216,  265,  233,  214,  213,  265,  265,    0,  207,  210,
      195,  204,    0,  265,  265,  204,  200,  189,  200,  191,
      186,  191,  185,  187,    0,  187,  195,  179,  185,  177,

      189,    0,  175,  181,  190,  174,   80,  180,  179,  265,
      109,  265,  205,  186,  105,    0,  265,  265,  265,  265,
        0,  167,  172,  178,   20,    0,  163,  176,  179,   78,
      174,  161,  172,  173,  173,  173,  165,    0,    0,  152,
      152,  164,  151,  154,  152,  161,    0,  152,  153,  128,
      265,  265,    0,  161,  146,  155,    0,  148,  143,  148,
      139,  147,    0,  150,  153,  135,  148,  140,  136,  144,
      132,    0,  138,  125,    0,    0,  138,  139,    0,  139,
      141,    0,  136,  122,    0,    0,  126,    0,  135,  128,
      135,    0,  131,  121,  120,  129,    0,    0,    0,  158,

      129,  111,  115,    0,  108,  118,  111,    0,    0,  106,
        0,    0,  150,    0,  104,   84,   95,    0,   74,    0,
       67,   45,    0,    0,    0,    0,  265,  130,  133,  137,
      139,  145
    } ;

static yyconst short int yy_def[233] =
    {   0,
      227,    1,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  228,  229,  227,  227,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  230,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  231,  231,  231,
      231,  231,  229,  227,  227,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  227,
      227,  227,  227,  227,  227,  230,  227,  227,  227,  227,
      231,  231,  231,  231,  231,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  227,
      227,  227,  231,  231,  231,  231,  231,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  232,  231,
      231,  231,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  229,  229,  229,  229,  232,

      231,  231,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  232,  231,  231,  229,  229,  229,  229,  229,
      231,  229,  229,  229,  231,  229,    0,  227,  227,  227,
      227,  227
    } ;

static yyconst short int yy_nxt[319] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
        4,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   28,   29,    4,   30,
       31,   32,   27,   33,   34,   27,   27,   35,   27,   36,
       37,   38,   39,   27,   40,   41,   42,   43,   27,   44,
       27,   27,   45,   49,   52,   54,   60,   57,   62,  156,
       50,   53,   63,   61,   55,   58,  157,   66,   64,   67,
       67,   56,   59,   73,   66,   65,   67,   67,   70,   71,
       75,   76,   92,   96,   79,   74,   72,   77,   80,   86,
      226,   81,   87,   88,   82,   93,   97,   99,  101,  104,

       94,  102,  100,   68,   48,  106,  113,  115,  115,  145,
      150,  225,  105,  107,   66,  224,   67,   67,  114,  111,
      111,  115,  115,  161,  162,  111,  111,  146,  223,  150,
      222,  147,  179,   78,   78,   83,   83,   83,   83,  116,
      116,  121,  121,  121,  121,  200,  221,  200,  200,  200,
      200,  213,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  201,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  184,  183,  182,
      181,  180,  178,  177,  176,  175,  174,  173,  172,  171,

      170,  169,  168,  167,  166,  165,  164,  163,  160,  159,
      158,  155,  154,  153,  152,  151,  149,  148,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  120,  119,  118,  117,  112,  110,   46,  109,  108,
      103,   98,   95,   91,   90,   89,   85,   84,   69,   51,
       48,   47,   46,  227,    3,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227
    } ;

static yyconst short int yy_chk[319] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   11,   14,   15,   17,   16,   18,  125,
       11,   14,   18,   17,   15,   16,  125,   19,   18,   19,
       19,   15,   16,   24,   20,   18,   20,   20,   23,   23,
       25,   25,   34,   36,   26,   24,   23,   25,   26,   30,
      222,   26,   30,   30,   26,   34,   36,   38,   39,   41,

       34,   39,   38,   19,   48,   42,   61,   66,   66,  107,
      111,  221,   41,   42,   67,  219,   67,   67,   61,   48,
       48,  115,  115,  130,  130,  111,  111,  107,  217,  150,
      216,  107,  150,  228,  228,  229,  229,  229,  229,  230,
      230,  231,  231,  231,  231,  232,  215,  232,  232,  232,
      232,  213,  210,  207,  206,  205,  203,  202,  201,  200,
      196,  195,  194,  193,  191,  190,  189,  187,  184,  183,
      181,  180,  178,  177,  174,  173,  171,  170,  169,  168,
      167,  166,  165,  164,  162,  161,  160,  159,  158,  156,
      155,  154,  149,  148,  146,  145,  144,  143,  142,  141,

      140,  137,  136,  135,  134,  133,  132,  131,  129,  128,
      127,  124,  123,  122,  114,  113,  109,  108,  106,  105,
      104,  103,  101,  100,   99,   98,   97,   96,   94,   93,
       92,   91,   90,   89,   88,   87,   86,   82,   81,   80,
       79,   75,   74,   73,   71,   60,   47,   46,   44,   43,
       40,   37,   35,   33,   32,   31,   29,   28,   21,   13,
        9,    7,    5,    3,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define INITIAL 0
// Lexical analyser of the Delta language.
// ScriptFighter Project.
// A. Savidis, Start October 1999.
// Updates for reading quoted strings and some refactoring, February 2009.
//

#include <cstring>
#include <cstdio>
#include <ctype.h>
#include <cstdarg>

#include "DDebug.h"
#include "Expr.h"
#include "Symbol.h"
#include "DeltaByteCodeTypes.h"
#include "ulexutil.h"
#include "DeltaCompErrorMsg.h"
#include "ASTNode.h"	//must be included before DeltaSyntax.h
#include "DeltaSyntax.h"
#include "ParseParms.h"
#include "CompilerStringHolder.h"
#include "ufunctors.h"

#define	YY_SKIP_YYWRAP
#define YY_USE_PROTOS
#define	YY_NEVER_INTERACTIVE 1

#define YY_DECL	int yyFlexLexer::yylex (YYSTYPE* yylval, YYLTYPE* yylloc)

#define SET_END_LOCATION							\
	yylloc->last_line = GET_PARSEPARMS.GetLine();	\
	yylloc->last_column = yypos

#define YY_USER_ACTION								\
	yylloc->first_line = GET_PARSEPARMS.GetLine();	\
	yylloc->first_column = yypos;					\
	yypos += yyleng;								\
	SET_END_LOCATION;

///////////////////////////////////////////////////////////
// Helper macros to get specific components from the lexer
// component directory.

#define GET_COMPMESSENGER	COMPMESSENGER_EX(GetDirectory())
#define GET_PARSEPARMS		PARSEPARMS_EX(GetDirectory())
#define GET_STRINGHOLDER	STRINGHOLDER_EX(GetDirectory())


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 228 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 265 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
return  FUNCTION;
	YY_BREAK
case 2:
YY_RULE_SETUP
return	RETURN;
	YY_BREAK
case 3:
YY_RULE_SETUP
return	ASSERT;
	YY_BREAK
case 4:
YY_RULE_SETUP
return	LAMBDA;
	YY_BREAK
case 5:
YY_RULE_SETUP
return	LAMBDA_REF;
	YY_BREAK
case 6:
YY_RULE_SETUP
return	ONEVENT;
	YY_BREAK
case 7:
YY_RULE_SETUP
return	METHOD;
	YY_BREAK
case 8:
YY_RULE_SETUP
return	SELF;
	YY_BREAK
case 9:
YY_RULE_SETUP
return	ARGUMENTS;
	YY_BREAK
case 10:
YY_RULE_SETUP
return	STATIC;
	YY_BREAK
case 11:
YY_RULE_SETUP
return	CONST;
	YY_BREAK
case 12:
YY_RULE_SETUP
return	IF;
	YY_BREAK
case 13:
YY_RULE_SETUP
return	ELSE;
	YY_BREAK
case 14:
YY_RULE_SETUP
return	WHILE;
	YY_BREAK
case 15:
YY_RULE_SETUP
return	FOR;
	YY_BREAK
case 16:
YY_RULE_SETUP
return	FOREACH;
	YY_BREAK
case 17:
YY_RULE_SETUP
return	NIL;
	YY_BREAK
case 18:
YY_RULE_SETUP
return	AND;
	YY_BREAK
case 19:
YY_RULE_SETUP
return	NOT;
	YY_BREAK
case 20:
YY_RULE_SETUP
return	OR;
	YY_BREAK
case 21:
YY_RULE_SETUP
return	TRUE;
	YY_BREAK
case 22:
YY_RULE_SETUP
return	FALSE;
	YY_BREAK
case 23:
YY_RULE_SETUP
return	BREAK;
	YY_BREAK
case 24:
YY_RULE_SETUP
return	CONTINUE;
	YY_BREAK
case 25:
YY_RULE_SETUP
return	LOCAL;
	YY_BREAK
case 26:
YY_RULE_SETUP
return	TRY;
	YY_BREAK
case 27:
YY_RULE_SETUP
return	TRAP;
	YY_BREAK
case 28:
YY_RULE_SETUP
return	THROW;
	YY_BREAK
case 29:
YY_RULE_SETUP
return	USING;
	YY_BREAK
case 30:
YY_RULE_SETUP
return	SET;
	YY_BREAK
case 31:
YY_RULE_SETUP
return	GET;
	YY_BREAK
case 32:
YY_RULE_SETUP
return	OPERATOR;
	YY_BREAK
case 33:
YY_RULE_SETUP
return	NEWSELF;
	YY_BREAK
case 34:
YY_RULE_SETUP
return	ATTRIBUTE;
	YY_BREAK
case 35:
YY_RULE_SETUP
return	STRINGIFY;
	YY_BREAK
case 36:
YY_RULE_SETUP
return	ADD;
	YY_BREAK
case 37:
YY_RULE_SETUP
return	SUB;
	YY_BREAK
case 38:
YY_RULE_SETUP
return	MUL;
	YY_BREAK
case 39:
YY_RULE_SETUP
return	DIV;
	YY_BREAK
case 40:
YY_RULE_SETUP
return	MOD;
	YY_BREAK
case 41:
YY_RULE_SETUP
return	GT;
	YY_BREAK
case 42:
YY_RULE_SETUP
return	LT;
	YY_BREAK
case 43:
YY_RULE_SETUP
return	NE;
	YY_BREAK
case 44:
YY_RULE_SETUP
return	EQ;
	YY_BREAK
case 45:
YY_RULE_SETUP
return	GE;
	YY_BREAK
case 46:
YY_RULE_SETUP
return	LE;
	YY_BREAK
case 47:
YY_RULE_SETUP
return	ASSIGN;
	YY_BREAK
case 48:
YY_RULE_SETUP
return	CALL;
	YY_BREAK
case 49:
YY_RULE_SETUP
return	CAST;
	YY_BREAK
case 50:
YY_RULE_SETUP
return	ADD_POSTFIX;
	YY_BREAK
case 51:
YY_RULE_SETUP
return	SUB_POSTFIX;
	YY_BREAK
case 52:
YY_RULE_SETUP
return	MUL_POSTFIX;
	YY_BREAK
case 53:
YY_RULE_SETUP
return	DIV_POSTFIX;
	YY_BREAK
case 54:
YY_RULE_SETUP
return	MOD_POSTFIX;
	YY_BREAK
case 55:
YY_RULE_SETUP
return	GT_POSTFIX;
	YY_BREAK
case 56:
YY_RULE_SETUP
return	LT_POSTFIX;
	YY_BREAK
case 57:
YY_RULE_SETUP
return	NE_POSTFIX;
	YY_BREAK
case 58:
YY_RULE_SETUP
return	EQ_POSTFIX;
	YY_BREAK
case 59:
YY_RULE_SETUP
return	GE_POSTFIX;
	YY_BREAK
case 60:
YY_RULE_SETUP
return	LE_POSTFIX;
	YY_BREAK
case 61:
YY_RULE_SETUP
return	GLOBAL_SCOPE;
	YY_BREAK
case 62:
YY_RULE_SETUP
return	PLUSPLUS;
	YY_BREAK
case 63:
YY_RULE_SETUP
return	MINUSMINUS;
	YY_BREAK
case 64:
YY_RULE_SETUP
return	DOT;
	YY_BREAK
case 65:
YY_RULE_SETUP
return	DOUBLE_DOT;
	YY_BREAK
case 66:
YY_RULE_SETUP
return	TRIPLE_DOT;
	YY_BREAK
case 67:
YY_RULE_SETUP
return	DOT_ASSIGN;
	YY_BREAK
case 68:
YY_RULE_SETUP
return	DOT_EQUAL;
	YY_BREAK
case 69:
YY_RULE_SETUP
return	DOT_EQUAL_RHS;
	YY_BREAK
case 70:
YY_RULE_SETUP
return	DOT_CAST;
	YY_BREAK
case 71:
YY_RULE_SETUP
return	DOUBLE_LB;
	YY_BREAK
case 72:
YY_RULE_SETUP
return	DOUBLE_RB;
	YY_BREAK
case 73:
YY_RULE_SETUP
return	ADD_A;
	YY_BREAK
case 74:
YY_RULE_SETUP
return	SUB_A;
	YY_BREAK
case 75:
YY_RULE_SETUP
return	MUL_A;
	YY_BREAK
case 76:
YY_RULE_SETUP
return	DIV_A;
	YY_BREAK
case 77:
YY_RULE_SETUP
return	MOD_A;
	YY_BREAK
case 78:
YY_RULE_SETUP
return	SEMI;
	YY_BREAK
case 79:
YY_RULE_SETUP
return META_LSHIFT;
	YY_BREAK
case 80:
YY_RULE_SETUP
return META_RSHIFT;
	YY_BREAK
case 81:
YY_RULE_SETUP
return META_ESCAPE;
	YY_BREAK
case 82:
YY_RULE_SETUP
return META_INLINE;
	YY_BREAK
case 83:
YY_RULE_SETUP
return META_EXECUTE;
	YY_BREAK
case 84:
YY_RULE_SETUP
return META_RENAME;
	YY_BREAK
case 85:
YY_RULE_SETUP
{}
	YY_BREAK
case 86:
YY_RULE_SETUP
{	GET_PARSEPARMS.NextLine(); SET_END_LOCATION; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{	ucastassign(yylval->numberConst, ustrdectodouble(yytext));
					return NUMBER_CONST;
				}
	YY_BREAK
case 88:
YY_RULE_SETUP
{	yylval->constStr = usaveidstr(yytext, &yy_id_buffer); return IDENT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{	yylval->constStr = usaveidstr(yytext, &yy_id_buffer); return ATTRIBUTE_IDENT; }
	YY_BREAK
case 90:
YY_RULE_SETUP
{	ucastassign(yylval->numberConst, ustrfracttodouble(yytext));
					return NUMBER_CONST;
				}
	YY_BREAK
case 91:
YY_RULE_SETUP
{	ucastassign(yylval->numberConst, ustrtohex(yytext + 2));
					return NUMBER_CONST;
				}
	YY_BREAK
case 92:
YY_RULE_SETUP
{	util_ui32 line;
					sscanf(yytext + 1, "%u", &line);
					GET_PARSEPARMS.SetLine(line);
					GET_COMPMESSENGER.SetCurrentFile(DNULLCHECK(strchr(yytext, '\"')) + 1);
					while (yyinput() != '\n'){} // Read until end of line.
					//TODO: what about location information?
				}
	YY_BREAK
case 93:
YY_RULE_SETUP
{	yylval->dynamicStr = GET_STRINGHOLDER.StringWithLateDestruction(ucopystr(ReadQuotedString()));
					SET_END_LOCATION;
					return STRING_CONST;
				}
	YY_BREAK
case 94:
YY_RULE_SETUP
{	IgnoreCStyleComments();		SET_END_LOCATION; }
	YY_BREAK
case 95:
YY_RULE_SETUP
{	IgnoreCPPStyleComments();	SET_END_LOCATION; }
	YY_BREAK
case 96:
YY_RULE_SETUP
return yytext[0];
	YY_BREAK
case 97:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 228 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 228 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 227);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


//------------------------------------------------------------------

int DeltaSyntax_yylex (YYSTYPE* yylval, YYLTYPE* yylloc, yyFlexLexer& lexer)
	{ return lexer.yylex(yylval, yylloc); }

char yyFlexLexer::yyinput_wrapper(void* closure) {
	yyFlexLexer* lexer = (yyFlexLexer*) closure;
	++lexer->yypos;
	return lexer->yyinput();
}

void yyFlexLexer::yyunput_wrapper(char c, void *closure) {
	yyFlexLexer* lexer = (yyFlexLexer*) closure;
	--lexer->yypos;
	lexer->yyunput(c, lexer->yytext_ptr);
}

void yyFlexLexer::IgnoreCStyleComments (void)  {
	util_ui32 line = GET_PARSEPARMS.GetLine();
	std::string error;
	bool result = uignoreCcomments(
		umakecallback(yyinput_wrapper, this),
		umakecallback(yyunput_wrapper, this),
		&line,
		&error
	);
	if (!result)
		GET_COMPMESSENGER.Error(error.c_str());
	GET_PARSEPARMS.SetLine(line);
} 

void yyFlexLexer::IgnoreCPPStyleComments (void) {
	if (uignoreCPPcomments(umakecallback(yyinput_wrapper, this)))
		GET_PARSEPARMS.NextLine();
}

const std::string yyFlexLexer::ReadQuotedString (void) {
	util_ui32 line = GET_PARSEPARMS.GetLine();
	std::string s;
	std::string error;
	if (!ureadquotedstring(s, umakecallback(yyinput_wrapper, this), &line, &error))
		GET_COMPMESSENGER.Error(error.c_str());
	GET_PARSEPARMS.SetLine(line);
	return uextendescapesequences(s.c_str());
}

//------------------------------------------------------------------
