/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DMSLEngine;

public class DecisionMaker {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public DecisionMaker(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DecisionMaker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        DMSLJNI.delete_DecisionMaker(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean Compile(String file) {
    return DMSLJNI.DecisionMaker_Compile(swigCPtr, this, file);
  }

  public boolean AppendRules(String file) {
    return DMSLJNI.DecisionMaker_AppendRules(swigCPtr, this, file);
  }

  public boolean LoadProfile(String profileFile) {
    return DMSLJNI.DecisionMaker_LoadProfile(swigCPtr, this, profileFile);
  }

  public boolean AppendProfile(String profileFile) {
    return DMSLJNI.DecisionMaker_AppendProfile(swigCPtr, this, profileFile);
  }

  public boolean Evaluate(String component, boolean force) {
    return DMSLJNI.DecisionMaker_Evaluate__SWIG_0(swigCPtr, this, component, force);
  }

  public boolean Evaluate(String component) {
    return DMSLJNI.DecisionMaker_Evaluate__SWIG_1(swigCPtr, this, component);
  }

  public boolean SetAttribute(String attribute, String value) {
    return DMSLJNI.DecisionMaker_SetAttribute(swigCPtr, this, attribute, value);
  }

  public boolean HasAttribute(String attribute) {
    return DMSLJNI.DecisionMaker_HasAttribute(swigCPtr, this, attribute);
  }

  public static java.math.BigInteger NewProfile(String profileFile) {
    return DMSLJNI.DecisionMaker_NewProfile__SWIG_0(profileFile);
  }

  public static java.math.BigInteger NewProfile() {
    return DMSLJNI.DecisionMaker_NewProfile__SWIG_1();
  }

  public static void DeleteProfile(java.math.BigInteger id) {
    DMSLJNI.DecisionMaker_DeleteProfile(id);
  }

  public static boolean AppendToProfile(java.math.BigInteger dest, java.math.BigInteger source) {
    return DMSLJNI.DecisionMaker_AppendToProfile(dest, source);
  }

  public static boolean SetProfileAttribute(java.math.BigInteger id, String attribute, String value) {
    return DMSLJNI.DecisionMaker_SetProfileAttribute(id, attribute, value);
  }

  public static boolean RemoveProfileAttribute(java.math.BigInteger id, String attribute) {
    return DMSLJNI.DecisionMaker_RemoveProfileAttribute(id, attribute);
  }

  public boolean AddProfile(java.math.BigInteger id) {
    return DMSLJNI.DecisionMaker_AddProfile(swigCPtr, this, id);
  }

  public boolean RemoveProfile(java.math.BigInteger id) {
    return DMSLJNI.DecisionMaker_RemoveProfile(swigCPtr, this, id);
  }

  public boolean WriteText(String file) {
    return DMSLJNI.DecisionMaker_WriteText(swigCPtr, this, file);
  }

  public StringVector GetStereotypes() {
    return new StringVector(DMSLJNI.DecisionMaker_GetStereotypes(swigCPtr, this), true);
  }

  public StringVector GetComponents() {
    return new StringVector(DMSLJNI.DecisionMaker_GetComponents(swigCPtr, this), true);
  }

  public String GetStereotypeDefinition(String id) {
    return DMSLJNI.DecisionMaker_GetStereotypeDefinition(swigCPtr, this, id);
  }

  public String GetComponentDefinition(String id) {
    return DMSLJNI.DecisionMaker_GetComponentDefinition(swigCPtr, this, id);
  }

  public StringVector GetDecisions() {
    return new StringVector(DMSLJNI.DecisionMaker_GetDecisions(swigCPtr, this), false);
  }

  public String GetSingleActivationDecision() {
    return DMSLJNI.DecisionMaker_GetSingleActivationDecision(swigCPtr, this);
  }

  public boolean ComponentDependsOnProfileAttribute(String component, String attribute) {
    return DMSLJNI.DecisionMaker_ComponentDependsOnProfileAttribute(swigCPtr, this, component, attribute);
  }

  public boolean ComponentDependsOnActivation(String component, String activation) {
    return DMSLJNI.DecisionMaker_ComponentDependsOnActivation(swigCPtr, this, component, activation);
  }

  public StringVector GetWarnings() {
    return new StringVector(DMSLJNI.DecisionMaker_GetWarnings(swigCPtr, this), false);
  }

  public void ClearWarnings() {
    DMSLJNI.DecisionMaker_ClearWarnings(swigCPtr, this);
  }

  public String GetError() {
    return DMSLJNI.DecisionMaker_GetError(swigCPtr, this);
  }

  public void ClearError() {
    DMSLJNI.DecisionMaker_ClearError(swigCPtr, this);
  }

  public static String GetGlobalError() {
    return DMSLJNI.DecisionMaker_GetGlobalError();
  }

  public static void ClearGlobalError() {
    DMSLJNI.DecisionMaker_ClearGlobalError();
  }

  public void ClearActivations() {
    DMSLJNI.DecisionMaker_ClearActivations(swigCPtr, this);
  }

  public boolean IsActiveComponent(String name) {
    return DMSLJNI.DecisionMaker_IsActiveComponent(swigCPtr, this, name);
  }

  public static boolean Initialize(String configFile) {
    return DMSLJNI.DecisionMaker_Initialize(configFile);
  }

  public static void Cleanup() {
    DMSLJNI.DecisionMaker_Cleanup();
  }

  public DecisionMaker() {
    this(DMSLJNI.new_DecisionMaker(), true);
  }

}
