/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package DMSLEngine;

class DMSLJNI {
  public final static native long new_StringVector__SWIG_0();
  public final static native long new_StringVector__SWIG_1(long jarg1);
  public final static native long StringVector_size(long jarg1, StringVector jarg1_);
  public final static native long StringVector_capacity(long jarg1, StringVector jarg1_);
  public final static native void StringVector_reserve(long jarg1, StringVector jarg1_, long jarg2);
  public final static native boolean StringVector_isEmpty(long jarg1, StringVector jarg1_);
  public final static native void StringVector_clear(long jarg1, StringVector jarg1_);
  public final static native void StringVector_add(long jarg1, StringVector jarg1_, String jarg2);
  public final static native String StringVector_get(long jarg1, StringVector jarg1_, int jarg2);
  public final static native void StringVector_set(long jarg1, StringVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_StringVector(long jarg1);
  public final static native boolean DecisionMaker_Compile(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native boolean DecisionMaker_AppendRules(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native boolean DecisionMaker_LoadProfile(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native boolean DecisionMaker_AppendProfile(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native boolean DecisionMaker_Evaluate__SWIG_0(long jarg1, DecisionMaker jarg1_, String jarg2, boolean jarg3);
  public final static native boolean DecisionMaker_Evaluate__SWIG_1(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native boolean DecisionMaker_SetAttribute(long jarg1, DecisionMaker jarg1_, String jarg2, String jarg3);
  public final static native java.math.BigInteger DecisionMaker_NewProfile__SWIG_0(String jarg1);
  public final static native java.math.BigInteger DecisionMaker_NewProfile__SWIG_1();
  public final static native void DecisionMaker_DeleteProfile(java.math.BigInteger jarg1);
  public final static native boolean DecisionMaker_AppendToProfile(java.math.BigInteger jarg1, java.math.BigInteger jarg2);
  public final static native boolean DecisionMaker_SetProfileAttribute(java.math.BigInteger jarg1, String jarg2, String jarg3);
  public final static native boolean DecisionMaker_RemoveProfileAttribute(java.math.BigInteger jarg1, String jarg2);
  public final static native boolean DecisionMaker_AddProfile(long jarg1, DecisionMaker jarg1_, java.math.BigInteger jarg2);
  public final static native boolean DecisionMaker_RemoveProfile(long jarg1, DecisionMaker jarg1_, java.math.BigInteger jarg2);
  public final static native boolean DecisionMaker_WriteText(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native long DecisionMaker_GetStereotypes(long jarg1, DecisionMaker jarg1_);
  public final static native long DecisionMaker_GetComponents(long jarg1, DecisionMaker jarg1_);
  public final static native String DecisionMaker_GetStereotypeDefinition(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native String DecisionMaker_GetComponentDefinition(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native long DecisionMaker_GetDecisions(long jarg1, DecisionMaker jarg1_);
  public final static native String DecisionMaker_GetSingleActivationDecision(long jarg1, DecisionMaker jarg1_);
  public final static native boolean DecisionMaker_ComponentDependsOnProfileAttribute(long jarg1, DecisionMaker jarg1_, String jarg2, String jarg3);
  public final static native boolean DecisionMaker_ComponentDependsOnActivation(long jarg1, DecisionMaker jarg1_, String jarg2, String jarg3);
  public final static native long DecisionMaker_GetWarnings(long jarg1, DecisionMaker jarg1_);
  public final static native void DecisionMaker_ClearWarnings(long jarg1, DecisionMaker jarg1_);
  public final static native String DecisionMaker_GetError(long jarg1, DecisionMaker jarg1_);
  public final static native void DecisionMaker_ClearError(long jarg1, DecisionMaker jarg1_);
  public final static native String DecisionMaker_GetGlobalError();
  public final static native void DecisionMaker_ClearGlobalError();
  public final static native void DecisionMaker_ClearActivations(long jarg1, DecisionMaker jarg1_);
  public final static native boolean DecisionMaker_IsActiveComponent(long jarg1, DecisionMaker jarg1_, String jarg2);
  public final static native boolean DecisionMaker_Initialize(String jarg1);
  public final static native void DecisionMaker_Cleanup();
  public final static native long new_DecisionMaker();
  public final static native void delete_DecisionMaker(long jarg1);
}
