// DeltaDebuggerFrontendDefs.h
// A. Savidis, June 2009.
//

#ifndef	DELTADEBUGERFRONTENDDEFS_H
#define	DELTADEBUGERFRONTENDDEFS_H

#include "utypes.h"


#if defined(DVMDEBUGFRONTEND_EXPORT) && defined(DVMDEBUGFRONTEND_IMPORT)
#error "Can't define both DVMDEBUGFRONTEND_EXPORT and DVMDEBUGFRONTEND_IMPORT!"
#endif

#if	defined(DVMDEBUGFRONTEND_EXPORT)
#define	DVMDEBUGFRONTEND_CLASS	UDLL_EXPORT_CPP_CLASS
#define	DVMDEBUGFRONTEND_FUNC	UDLL_EXPORT_CPP
#define	DVMDEBUGFRONTEND_CFUNC	UDLL_EXPORT_C
#elif defined(DVMDEBUGFRONTEND_IMPORT)
#define	DVMDEBUGFRONTEND_CLASS	UDLL_IMPORT_CPP_CLASS
#define	DVMDEBUGFRONTEND_FUNC	UDLL_IMPORT_CPP
#define	DVMDEBUGFRONTEND_CFUNC	UDLL_IMPORT_C
#else
#define	DVMDEBUGFRONTEND_CLASS
#define	DVMDEBUGFRONTEND_FUNC extern
#define	DVMDEBUGFRONTEND_CFUNC extern
#endif

#endif	// Do not add stuff beyond this point.

